spring:
  rabbitmq:
    host: 47.94.169.13
    port: 5675
    virtual-host: /
    username: user
    password: 111111
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://47.94.169.13:3306/ityustudy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 47.94.169.13 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    jedis:
     pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000 # 连接超时时间（毫秒）
  data:
    mongodb:
#      port: 27017
#      host: 47.94.169.13
#      username: root
#      password: 111111
#      authentication-database: admin
#      database: admin
      uri: mongodb://root:111111@47.94.169.13:27017/admin?main?authSource=admin&authMechanism=SCRAM-SHA-1
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
rediskey:
  prefix:
    authCode: "portal:authCode:"
    orderId: "portal:orderId:"
  expire:
    authCode: 90 # 验证码超期时间druid
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.ityu.mall: debug
#  file: demo_log.log #配置日志生成路径
server:
  port: 8086
#  path: /var/logs #配置日志文件名称